# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branch: [CICD]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: horochx/deploy-via-scp@master
        with:
          local: localPath # eg: dist/*
          remote: ${{ secrets.REMOTE }} # eg: /home/github-action/www
          host: ${{ secrets.HOST }} # eg: example.com
          port: ${{ secrets.PORT }} # eg: 22
          user: ${{ secrets.USER }} # eg: github-action
          key: ${{ secrets.KEY }} # eg: -----BEGIN OPENSSH PRIVATE KEY-----\nHEIiyzh5cT7hN...
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm start
