# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Automation Deployment

on:
  push:
    branches: [CICD]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy source code
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/simple-nodejs/simple-nodejs
          remote: /home/yunandar/projects/simple-nodejs
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          run: pwd
      - name: Deploy Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: bash /home/yunandar/projects/simple-nodejs/deploy.sh
